#!/usr/bin/env python3
"""
sync_skills.py — Sync mod skill docs to workspace cache.

Usage:
    python sync_skills.py [--port PORT] [--cache-dir DIR]

Workflow:
    1. Call C# get_env_info to discover each mod's skillPath
    2. Incrementally copy .md files to .cache/skills_cache/{assemblyName}/
    3. Generate MASTER_INDEX.md with relative links
"""

import sys
import os
import json
import shutil
import http.client
from pathlib import Path

DEFAULT_PORT = 3100
DEFAULT_CACHE_DIR = ".cache/skills_cache"
MANIFEST_NAME = ".manifest.json"
INDEX_NAME = "MASTER_INDEX.md"


def resolve_auth_token() -> str:
    """Scan possible paths for ModConfig.json to extract MCPAuthToken."""
    candidates = [
        os.environ.get("MCP_MOD_TOKEN", ""),
    ]
    # Relative to this script
    script_dir = Path(__file__).resolve().parent
    for p in [script_dir / "【MOD文件夹】", script_dir.parent / "【MOD文件夹】"]:
        candidates.append(str(p / "ModConfig.json"))

    for c in candidates:
        if not c:
            continue
        p = Path(c)
        if p.exists():
            try:
                cfg = json.loads(p.read_text(encoding="utf-8"))
                tok = cfg.get("MCPAuthToken", "")
                if tok:
                    return tok
            except (json.JSONDecodeError, OSError):
                pass
    return ""


def call_get_env_info(port: int, token: str = "") -> dict:
    """Call the C# server's get_env_info tool."""
    body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": "get_env_info"})
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    try:
        conn = http.client.HTTPConnection("localhost", port, timeout=10)
        conn.request("POST", "/", body, headers)
        resp = conn.getresponse()
        data = json.loads(resp.read().decode("utf-8"))
        conn.close()
    except Exception as e:
        print(f"ERROR: Cannot reach C# server on port {port}: {e}", file=sys.stderr)
        sys.exit(1)

    err = data.get("Error") or data.get("error")
    if err:
        code = err.get("code", "") if isinstance(err, dict) else ""
        msg = err.get("message", str(err)) if isinstance(err, dict) else str(err)
        print(f"ERROR from server (code={code}): {msg}", file=sys.stderr)
        if code == -32001:
            print("HINT: Missing or invalid auth token. Set MCP_MOD_TOKEN env var.", file=sys.stderr)
        sys.exit(1)

    result = data.get("Result") or data.get("result") or {}
    return result


def compute_fingerprint(dir_path: str) -> dict:
    """Build a dict of {relative_path: [mtime, size]} for all .md files."""
    fp = {}
    base = Path(dir_path)
    if not base.is_dir():
        return fp
    for f in sorted(base.rglob("*.md")):
        rel = str(f.relative_to(base))
        st = f.stat()
        fp[rel] = [st.st_mtime, st.st_size]
    return fp


def load_manifest(cache_dir: str) -> dict:
    mf = Path(cache_dir) / MANIFEST_NAME
    if mf.exists():
        try:
            return json.loads(mf.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def save_manifest(cache_dir: str, fp: dict):
    mf = Path(cache_dir) / MANIFEST_NAME
    mf.parent.mkdir(parents=True, exist_ok=True)
    mf.write_text(json.dumps(fp, indent=2), encoding="utf-8")


def sync_namespace(assembly_name: str, source_path: str, cache_dir: str) -> bool:
    src = Path(source_path)
    dst = Path(cache_dir) / assembly_name

    if not src.is_dir():
        return False

    current_fp = compute_fingerprint(source_path)
    manifest_key = f"{assembly_name}:{os.path.abspath(source_path)}"
    manifest_path = Path(cache_dir) / MANIFEST_NAME

    old_manifest = load_manifest(cache_dir)
    old_fp = old_manifest.get(manifest_key, {})

    target_fp = compute_fingerprint(str(dst)) if dst.exists() else {}

    if current_fp == old_fp and current_fp == target_fp:
        return False

    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(str(src), str(dst), dirs_exist_ok=True)

    old_manifest[manifest_key] = current_fp
    save_manifest(cache_dir, old_manifest)

    n = len(current_fp)
    print(f"  synced {assembly_name}: {n} .md file(s)")
    return True


def generate_master_index(modules: list, cache_dir: str):
    lines = [
        "# MASTER_INDEX — Mod Skill Documentation",
        "",
        "Auto-generated by sync_skills.py. Lists all available mod skill documentation.",
        "",
    ]

    for mod in modules:
        asm_name = mod.get("assemblyName")
        skill_path = mod.get("skillPath")
        if not asm_name or not skill_path:
            continue

        dst = Path(cache_dir) / asm_name
        if not dst.is_dir():
            continue

        md_files = sorted(dst.rglob("*.md"))
        if not md_files:
            continue

        lines.append(f"## {asm_name}")
        lines.append("")

        for md in md_files:
            rel = os.path.relpath(str(md), cache_dir)
            title = md.stem
            try:
                content = md.read_text(encoding="utf-8", errors="replace")
                for line in content.splitlines():
                    s = line.strip()
                    if s.startswith("# "):
                        title = s[2:].strip()
                        break
            except OSError:
                pass
            lines.append(f"- [{title}]({rel})")

        lines.append("")

    idx_path = Path(cache_dir) / INDEX_NAME
    idx_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  generated {idx_path}")


def main():
    port = DEFAULT_PORT
    cache_dir = DEFAULT_CACHE_DIR
    token = resolve_auth_token()

    args = list(sys.argv[1:])
    while args:
        if args[0] == "--port" and len(args) >= 2:
            port = int(args[1])
            args = args[2:]
        elif args[0] == "--cache-dir" and len(args) >= 2:
            cache_dir = args[1]
            args = args[2:]
        else:
            print(f"Unknown arg: {args[0]}", file=sys.stderr)
            sys.exit(1)

    # Allow env var override
    token = os.environ.get("MCP_MOD_TOKEN", token)

    if token:
        print(f"Auth token resolved, connecting to localhost:{port}...")
    else:
        print(f"No auth token found, connecting to localhost:{port} (may fail if mod requires auth)...")

    env_info = call_get_env_info(port, token)
    active_modules = env_info.get("activeModules") or []

    if not active_modules:
        print("No modules with skill paths found.")
        return

    print(f"Found {len(active_modules)} module(s) with skill metadata.")

    cache_root = Path(cache_dir)
    cache_root.mkdir(parents=True, exist_ok=True)

    changed = False
    for mod in active_modules:
        asm_name = mod.get("assemblyName")
        skill_path = mod.get("skillPath")
        if not asm_name or not skill_path:
            continue
        if not os.path.isdir(skill_path):
            continue

        if sync_namespace(asm_name, skill_path, str(cache_root)):
            changed = True

    if changed or not (cache_root / INDEX_NAME).exists():
        generate_master_index(active_modules, str(cache_root))
    else:
        print("No changes detected. MASTER_INDEX already up-to-date.")

    print(f"\nDone. Skills cached in: {os.path.abspath(cache_dir)}")
    print(f"Open {os.path.abspath(cache_dir)}/{INDEX_NAME} to browse.")


if __name__ == "__main__":
    main()
