#!/usr/bin/env python3
"""
skill_sync — Sync mod skill docs to workspace and global opencode skills directory.

Used by the gateway on first heartbeat to automatically pull skill documentation
from the game mod's install directory into the developer's workspace.
"""

import json
import os
import shutil
from pathlib import Path


MANIFEST_NAME = ".manifest.json"
INDEX_NAME = "MASTER_INDEX.md"


def compute_fingerprint(dir_path: str) -> dict:
    """Build a dict of {relative_path: [mtime, size]} for all .md files."""
    fp = {}
    base = Path(dir_path)
    if not base.is_dir():
        return fp
    for f in sorted(base.rglob("*.md")):
        rel = str(f.relative_to(base))
        st = f.stat()
        fp[rel] = [st.st_mtime, st.st_size]
    return fp


def load_manifest(cache_dir: str) -> dict:
    mf = Path(cache_dir) / MANIFEST_NAME
    if mf.exists():
        try:
            return json.loads(mf.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def save_manifest(cache_dir: str, fp: dict):
    mf = Path(cache_dir) / MANIFEST_NAME
    mf.parent.mkdir(parents=True, exist_ok=True)
    mf.write_text(json.dumps(fp, indent=2), encoding="utf-8")


def sync_namespace(assembly_name: str, source_path: str, target_dir: str) -> bool:
    src = Path(source_path)
    dst = Path(target_dir)

    if not src.is_dir():
        return False

    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(str(src), str(dst), dirs_exist_ok=True)
    return True


def generate_master_index(modules: list, cache_dir: str):
    lines = [
        "# MASTER_INDEX — Mod Skill Documentation",
        "",
        "Auto-generated by skill_sync.py. Lists all available mod skill documentation.",
        "",
    ]

    for mod in modules:
        asm_name = mod.get("assemblyName")
        dst = Path(cache_dir) / asm_name
        if not dst.is_dir():
            continue

        md_files = sorted(dst.rglob("*.md"))
        if not md_files:
            continue

        lines.append(f"## {asm_name}")
        lines.append("")

        for md in md_files:
            rel = os.path.relpath(str(md), cache_dir)
            title = md.stem
            try:
                content = md.read_text(encoding="utf-8", errors="replace")
                for line in content.splitlines():
                    s = line.strip()
                    if s.startswith("# "):
                        title = s[2:].strip()
                        break
            except OSError:
                pass
            lines.append(f"- [{title}]({rel})")

        lines.append("")

    idx_path = Path(cache_dir) / INDEX_NAME
    idx_path.write_text("\n".join(lines), encoding="utf-8")


def sync_skill_docs(
    heartbeat_response: dict,
    local_skills_dir: str,
    global_skills_dir: str | None = None,
) -> dict:
    """
    Sync skill docs from mod's install directory to workspace and optionally
    to the global opencode skills directory.

    Args:
        heartbeat_response: The /heartbeat response from the mod, containing
                           'activeModules' with assemblyName and skillPath.
        local_skills_dir:   Workspace .agents/skills/ directory.
        global_skills_dir:  Optional ~/.config/opencode/skills/ directory.

    Returns:
        { 'synced': {assembly_name: count}, 'errors': [...] }
    """
    active_modules = heartbeat_response.get("activeModules") or []
    result = {"synced": {}, "errors": []}

    if not active_modules:
        result["errors"].append("No active modules in heartbeat response")
        return result

    local_root = Path(local_skills_dir)
    local_root.mkdir(parents=True, exist_ok=True)

    targets = [(local_root, "local")]
    if global_skills_dir:
        global_root = Path(global_skills_dir)
        global_root.mkdir(parents=True, exist_ok=True)
        targets.append((global_root, "global"))

    for mod in active_modules:
        asm_name = mod.get("assemblyName")
        skill_path = mod.get("skillPath")
        if not asm_name or not skill_path:
            continue
        if not os.path.isdir(skill_path):
            result["errors"].append(f"{asm_name}: skillPath not found ({skill_path})")
            continue

        for root, label in targets:
            target_dir = root / asm_name
            sync_namespace(asm_name, skill_path, str(target_dir))

        md_count = len(list(Path(skill_path).rglob("*.md")))
        result["synced"][asm_name] = md_count

    generate_master_index(active_modules, str(local_root))
    return result